config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 2, maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }

  has_many :articles

  before_save { self.email = email.downcase }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user

  def current_user
    current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action!"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show, :destroy, :update]

  def new
    @article = Article.new
  end

  def index
    @all_articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = "Article was successfully saved!"
      redirect_to article_path(@article)
    else
      flash[:error] = "Article was not saved!"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @article.user = User.last
    if @article.update(article_params)
      flash[:success] = "Article was updated successfully!"
      redirect_to article_path(@article)
    else
      flash[:error] = "Article not updated!"
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "Article was deleted!"
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in Successfully!"
      redirect_to users_path(user)
    else
      flash[:danger] = "Something wrong with login credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out Successfully!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

  def new
    @user = User.new
  end

  def index
    @all_users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Rails blog #{@user.user_name}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.user_name, class: "img-circle")
 end
end

app/views/articles/_articles.html.erb
<% if obj.present? %>
  <% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <small>
            Created by: <%= article.user.user_name if article.user %>,
            <%= time_ago_in_words(article.created_at) %> ago,
            last updated: <%= time_ago_in_words(article.updated_at) %> ago
        </small>
        <div class="article-body">
        <%= truncate(article.description, length: 100) %>
        </div>
        <div class="article-actions">
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
  <h4>No Articles found!</h4>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article!</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div align="center">
  <h1>Articles Index page!</h1>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Create New Article', new_article_path %>

  <%= will_paginate @all_articles %>
  <%= render 'articles', obj: @all_articles %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article form page!</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="text-center">
<% if @article.user %>
<ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
    <li class="article-title"><%= link_to @article.user.user_name, user_path(@article.user) %></li>
    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
   </div>
  </div>
 </ul>
 <% end %>
  <h2>Title: <%= @article.title %></h2>
  <small>
    Created by: <%= @article.user.user_name if @article.user %>,
    <%= time_ago_in_words(@article.created_at) %> ago,
    last updated: <%= time_ago_in_words(@article.updated_at) %> ago
  </small>
</div>
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
<%= simple_format(@article.description) %>
<%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
<%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rails Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>

    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
          <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
        <% end %>
      </div>
    </div>
    
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About page of Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <h1>Welcome to Blog! Hurrah!!!!</h1>
    <%= link_to 'About', about_path, class: "btn btn-xs btn-secondary" %>
    <%= link_to 'Articles', articles_path, class: "btn btn-xs btn-primary" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
      <h2 class="panel-title">
        <%= pluralize(obj.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <div class="panel-body">
        <ul>
        <% obj.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      </div>
    </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :user_name %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :user_name, class: "form-control", placeholder: "Enter User Name", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
  </div> 
 </div>
</div>

app/views/users/edit.html.erb
<h1>Edit User Details</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div align="center">
<h1 align="center">All Users</h1>
<%= will_paginate @all_users %>
<% @all_users.each do |user| %>
 <ul class="listing">
  <div class="row">
   <div class="well col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(user), user_path(user) %></li>
    <li class="article-title"><%= link_to user.user_name, user_path(user) %></li>
    <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
   </div>
  </div>
 </ul>
<% end %>
</div>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<% if logged_in? %>
<h1 align="center">Welcome to <%= @user.user_name %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user %>
  </div>
</div>
<h4 align="center"><%= @user.user_name %>'s articles</h4>
<div class="center">
 <%= will_paginate @user_articles %>
</div>
<%= render 'articles/articles', obj: @user_articles %>
<div class="center">
 <%= will_paginate @user_articles %>
</div>
<% else %>
<%= require_user %>
<%end%>